### ISSUE TITLE
Avoid confusion with the name "Vanilla"

### ISSUE THREAD

**Issue by sylvainpolletvillard** [thephuse/vanilla-modal#1]
In computer software, "vanilla" stands for standard without customization. That's why I was expecting that this library uses the standard element for modal windows, ie &lt;dialog&gt; and showModal(). 

I do not want to debate whether this method is better than plain old &lt;div&gt; or not, but I think it should be clearly stated in the introduction in order to avoid confusion.

**Comment by benceg** [comment]
Hi Sylvain,

I'm not going to split hairs over semantics, suffice it to say that "[vanilla](https://www.google.com/search?q=define+vanilla)" in this context relates to the fact that no extraneous libraries are used—i.e. that this modal is written in plain JavaScript and carries no dependencies. I feel this is made [pretty clear](user-content-why-plain-javascript) in the intro. The name is likewise a complimentary allusion to the tongue-in-cheek [Vanilla JS](http://vanilla-js.com/) website.
