### ISSUE TITLE
Possible error in readme

### ISSUE THREAD

**Issue by voveson** [thephuse/vanilla-modal#11]
First, major kudos for this library!  

It's possible I missed something obvious, but I was not able to instantiate a modal using the example in the readme.  I kept getting a console error saying `VanillaModal is not defined`.

The readme says to do it like this:  `const modal = new VanillaModal(options);` but I noticed that in your demo you do:  `const modal = new vanillaModal.VanillaModal(options);`.  This is what ultimately ended up working for me.

**Comment by benceg** [comment]
Hi @voveson,

You're dead right - depending on how you've imported the script, yourcall to it will vary. It's a caveat of Babel 6's UMD implementation, which I need to document. Thanks so much for raising this. And thank you for the kudos!

**Comment by benceg** [comment]
Hi @voveson,

Drawing back to this issue, the method specified in the readme is now correct.
