### ISSUE TITLE
Issue with the import

### ISSUE THREAD

**Issue by joshycube** [thephuse/vanilla-modal#14]
import {VanillaModal} from 'vanilla-modal';
const modal = new VanillaModal({});

says Uncaught TypeError: _vanillaModal.VanillaModal is not a constructor

**Comment by partikule** [comment]
try : 
`var myModal = new vanillaModal.VanillaModal({});`

**Comment by benceg** [comment]
Thanks for stepping in there @partikule.

I'm working on a partial rewrite today, which will resolve this issue.

**Comment by benceg** [comment]
Hi @joshycube and @partikule,

This had to do with the update to Babel 6. I've since fixed it. You'll want to update to `1.3.0` and refactor to the following:

```js
import VanillaModal from 'vanilla-modal';
const modal = new VanillaModal();
```

**Comment by SteveQ88** [comment]
Hi I am also getting the error:
Uncaught TypeError: VanillaModal is not a constructor

I am creating a new instance of the modal with 
const VanillaModal = require('vanilla-modal');
        const modal = new VanillaModal({
            clickOutside : false
        });

I am also using gulp, browserify and babelify... in my babelrc I have the preset es2015

If i am being thick please could you point me in the right direction?

Steve
