### ISSUE TITLE
replacement content 

### ISSUE THREAD

**Issue by smoruetasantiago** [thephuse/vanilla-modal#17]
Hi!

Just wondering if could be possible to have a public method to replace current content of modal by other one, but keeping opened the same modal itself. 

I've been checking the library and I found `_releaseNode ` method, that does exactly what I need, although calling it directly the current property is not updated. Could  be created a public property that refers this method and update whatever is need around this change?

**Comment by benceg** [comment]
Hi @smoruetasantiago,

You can do this already by using `modal.open`. Try it out on the [demo page](http://thephuse.github.io/vanilla-modal/):

1. Open the developer console.

2. Type `modal.open('#modal-1')`, hit <enter>.

3. Type `modal.open('#modal-2')`, hit <enter>.

You'll see that using `modal.open` will release the current DOM node and replace the content in the modal with that of the element provided to it as an argument.

**Comment by benceg** [comment]
I'm closing this issue for now @smoruetasantiago. I hope the solution above worked for you. Please let me know if you need any further support.
