### ISSUE TITLE
how to clear the existing modal contents before modal.load()

### ISSUE THREAD

**Issue by busla** [thephuse/vanilla-modal#20]
My use case is this:

I have a get() request each time a modal is loaded but I can´t seem to clear existing content without a hack.

Any ideas?

**Comment by sixthcore** [comment]
There are two hooks:  onBeforeClose / onClose 

That may potentially help you out there by allowing you to script in a destory/clear/sanetize depending on what you would need to achieve.

A full list of options are available on here :)

https://github.com/thephuse/vanilla-modal

**Comment by busla** [comment]
Thanks for replying so quickly.

Seems that those hooks don´t call the defined function:

```
var clearModalContent = function() {
  console.log('clear content');
};

const modal = new VanillaModal({
  onClose: clearModalContent()
});
```

**Comment by busla** [comment]
Opps, sorry mate. Needed an anonymous function there :-)

This works:

```
var clearModalContent = function() {
  console.log('clear content');
};

const modal = new VanillaModal({
  onClose: function() {
    clearModalContent()
  }
});
```

**Comment by sixthcore** [comment]
All good! Re open if you need :)
