### ISSUE TITLE
transitions: false does not seem to turn off transitions

### ISSUE THREAD

**Issue by hchoriq** [thephuse/vanilla-modal#25]
<script>var modal = new VanillaModal.default({transitions: false});</script>

I still see transitions

**Comment by benceg** [comment]
Hi @hchoriq,

`transitions: false` will not remove transitions from your CSS. What it will do, however, is not wait until a closing transition has completed ahead of closing the modal. If you want to remove transitions altogether, you'll have to get rid of them in the CSS.

**Comment by benceg** [comment]
Closing this issue. Hope the above helped @hchoriq.
