### ISSUE TITLE
Prevent modal closing

### ISSUE THREAD

**Issue by makedonec88** [thephuse/vanilla-modal#26]
Hi guys.
I have modal with form inside, and if form not submitted and user want to close it I want to throw him a `confirm()` box with some text like 'Are you sure ?'. And depends on true/false close it or not.
I've found `onBeforeClose` method in documentation, but I have problem with preventing closing. Even though it recieve `click` or `keydown` event, I can't prevent it with 'traditional' technics like preventDefault or returning false;
So, any Idea how to do it ?

**Comment by panoply** [comment]
If you are loading the  `confirm()` within the `modal-content` element, there is no reason for the modal to close, If I understand correctly, you just want to initialise a prompt or alert within the modal before submitting the form. 

Within `modal-content` just attach an event to the click of button and on the click, simply display a hidden div, rough eg:

```
<form>
<input type="text>
etc etc 
</div>
<button type ="button" id="confirm-prompt">
Submit Form
</button>

<div class="prompt">
</div>

```

```
.prompt {
   display:none;
   position:absolute;
   top:0;
   left:0;
   right:0;
   bottom:0;
  background: rgba(0,0,0,0.5);
  color:white;
}
```

```
var prompt = document.getElementById('confirm-prompt');
var showPrompt = document.getElementById('show-prompt'); // id of css div for overlay
prompt.addEventListener('click', function(e) {
      e.preventDefault();
      showPrompt.style.display = 'block';
 });
```

**Comment by panoply** [comment]
Side note, use stackoverflow dude.

**Comment by makedonec88** [comment]
@panoply Thank you for your response.I'm sorry, but It looks like, I wasn't really clear. And my example with form made it even more confused.
So. in a nutshell. when user trying to close modal window (by clicking close button or clicking outside of modal window), I want to have opportunity to prevent this closing.

**Comment by panoply** [comment]
man, post on stack.

**Comment by benceg** [comment]
Hi @makedonec88,

You could toggle the CSS selector of your `close` item.

An example:

```js
const modal = new VanillaModal({
  close: '.closeButton.isActive',
});
```

```html
<button class="closeButton">Close</button>
```

And have a successful validation callback from your form's validation handler, which adds an `isActive` class to the button. I'm not sure what validation methodology you're using, but here's a very basic example to illustrate the solution:

```js
myForm.validate({
  success: () => {
    // If an error subsequently occurs, remove the `isActive` class
    document.querySelector('.closeButton').classList.add('isActive');
  },
  error: () => {
    // If an error subsequently occurs, remove the `isActive` class
    document.querySelector('.closeButton').classList.remove('isActive');
  }
});
```

Since the `open` and `close` DOM listeners are delegated from the `document` root node, you can quite safely inject them into and remove them from the DOM according to your needs.
