### ISSUE TITLE
Missing tags?

### ISSUE THREAD

**Issue by tomeightyeight** [thephuse/vanilla-modal#27]
It seems the 1.3.* tags for this have just vanished?

**Comment by benceg** [comment]
Tom! Sorry, that's a bit of a nightmare. I assure you we haven't tried to vanish them. [CDNJS](https://cdnjs.com/libraries/vanilla-modal) should have the version you need. 1.3.x came before Bower support, so a download ought to be sufficient for your use case, given that it's a single file.

Having said that, the latest version contains a few overall performance improvements, legibility enhancements, and a subtly improved fragrance, so if you don't mind changing one or two default settings (see the readme), an update might suit your needs perfectly.

**Comment by tomeightyeight** [comment]
No problem - we have updated - it was worth it for the new fragrance!
