### ISSUE TITLE
Body overflow:hidden delay

### ISSUE THREAD

**Issue by ezhkov** [thephuse/vanilla-modal#29]
Hi. Could you please tell me how to set delay before body becomes overflow:hidden. Page content shifts, when I click the trigger link, before the modal appears.
My modal appears with animation and I want to remove scrolls AFTER modal fully appeared.

**Comment by benceg** [comment]
Hi @ezhkov,

You can use the `onOpen` and `onClose` hooks.

```js
const modal = new VanillaModal({
  onOpen: () => {
    document.body.classList.add('hide-overflow');
  },
  onClose: () => {
    document.body.classList.remove('hide-overflow');
  }
});
```

**Comment by benceg** [comment]
P.S. Use `setTimeout` if you need to delay the addition or removal of that class.
