### ISSUE TITLE
data-attribute

### ISSUE THREAD

**Issue by marcobiedermann** [thephuse/vanilla-modal#3]
Really nice and simple plugin. I like it :)

In my opinion using the data-attribute instead of `rel="modal:*"` might be a better approach because most plugins use this for configuration. More programmers are used to this syntax

**Comment by benceg** [comment]
Hi Marco,
Thanks for the kudos! The triggers are configurable (info in the docs) and can very easily use data-attributes instead of the rel syntax. I won't change the default behaviour as it may break current implementations.

**Comment by marcobiedermann** [comment]
@benceg Alright, Thank you very much for the quick reply!
