### ISSUE TITLE
Any plans for hash tracking?

### ISSUE THREAD

**Issue by danielpost** [thephuse/vanilla-modal#30]
Hi there,

I'm trying to move away from [Remodal](https://vodkabears.github.io/remodal/), but I do need hash tracking to work. Are there any plans to support this is in the future? And if not, could you point me in the right direction to get started?

Thanks!

**Comment by panoply** [comment]
If memory calls me correct most devs used Remodal's hash tracking feature so as to init the modal upon page load. If that is to be your case, then:
 

Init on page load:

```
var modal = new VanillaModal.default();
document.addEventListener('DOMContentLoaded', function(){ 
    return modal.open('#modal-to-open');
}, false);
```
