### ISSUE TITLE
Matching loops break for dynamically added content

### ISSUE THREAD

**Issue by aschmi** [thephuse/vanilla-modal#7]
Hi,

First of all, I like your modal implementation very much. Thank you for your efforts!

However, I'm having errors with two functions, namely `OutsideClickHandler` and `Matches`.
see: https://github.com/thephuse/vanilla-modal/blob/master/src/vanilla-modal.js#L239

The error message is: ```Uncaught TypeError: Cannot read property 'parentNode' of null```

The Error occurs, when I click on elements which have been added to the DOM dynamically and have click callback registered (by jQuery's `append(…)` and `click(…`). 
In the while-loops it seems that these elements are orphaned (which they are not) which ultimately leads to `child` or `node` being `null` instead of body. In this case `.parentNode` is called on `null`.

My quick fix would be to add checks for `node` and `child` in the while-loops.

```while (node && node != document.body) { … }```

```while (child && child != document.body) { … }```

Do you see any problems with that?

**Comment by benceg** [comment]
Hi @aschmi,

I think this might be symptomatic of a slightly bigger contextual issue. I'll investigate it as soon as I have the time. Thanks for flagging the problem!

**Comment by alisonjoseph** [comment]
Running into a similar issue, Thanks for the fix aschi!
