### ISSUE TITLE
Demo link on readme is broken

### ISSUE THREAD

**Issue by pedrocanterini** [thephuse/vanilla-modal#8]
I don't mind sending a PR with a demo hosted by jsbin or similar if that would be useful.

**Comment by benceg** [comment]
Thanks for the tip @pedrocanterini. I've added the demo to the `gh-pages` branch, so it's now accessible at http://thephuse.github.io/vanilla-modal.

**Comment by pcanterini** [comment]
@benceg cool, the link on [Phuse](http://phuse.ca/vanilla-modal-plain-javascript-modal/) might also need to be updated.

**Comment by benceg** [comment]
Right you are @pedrocanterini; that's updated. Thanks again!
